# Dockerfile (Backend)
FROM node:18-alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .

# If your Strapi uses SQLite (default), no need for extra DB config here

RUN npm run build

EXPOSE 1337

CMD ["npm", "run", "start"]
